---
- hosts: buildservers
  user: vagrant
  sudo: yes

  vars_files:
     - vars/default.yml

  roles:
    - hosts
    - common
    - ansible-java8-oracle
    - jenkins
    - hubot

  environment:
    "{{ (with_proxy) | ternary( proxy_env, {}) }}"   # use proxy_env only when with_proxy is true
